In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"D:\externship\bank.csv")

In [3]:
dataset.head(2)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   
1   56  admin.  married  secondary      no       45      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
a = dataset.iloc[:,0:9]
b = dataset.iloc[:,11:13]
c = dataset.iloc[:,14:16]

In [6]:
x = a.join(b)
x = x.join(c)

In [7]:
x = x.values
y = dataset.iloc[:,16:].values

In [8]:
x[0]

array([59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 1042, 1, 0, 'unknown'], dtype=object)

In [9]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,12])],remainder ="passthrough")
x = ct.fit_transform(x)

In [12]:
ct1 = ColumnTransformer([("one",OneHotEncoder(),[0])],remainder ="passthrough")
y = ct1.fit_transform(y)

In [13]:
x[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 1042, 1, 0], dtype=object)

In [14]:
y[80]

array([0., 1.])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
categorical = Sequential()

In [19]:
x_train.shape

(8929, 37)

In [20]:
y_train.shape

(8929, 2)

In [21]:
categorical.add(Dense( units= 37, kernel_initializer= "random_uniform", activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [22]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [23]:
categorical.add(Dense( units= 2, kernel_initializer= "random_uniform", activation="softmax"))

In [24]:
categorical.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics=["accuracy"])

In [25]:
categorical.fit(x_train, y_train, epochs = 350)

Epoch 1/350
8929/8929 [==============================] - 0s 49us/sample - loss: 0.4751 - acc: 0.7809
Epoch 2/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.4171 - acc: 0.8143
Epoch 3/350
8929/8929 [==============================] - 0s 33us/sample - loss: 0.4101 - acc: 0.81680s - loss: 0.4122 - acc: 0.816
Epoch 4/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.4075 - acc: 0.81910s - loss: 0.4079 - acc: 0.819
Epoch 5/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.4034 - acc: 0.8191
Epoch 6/350
8929/8929 [==============================] - ETA: 0s - loss: 0.4012 - acc: 0.821 - 0s 32us/sample - loss: 0.4018 - acc: 0.8202
Epoch 7/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.3999 - acc: 0.8199
Epoch 8/350
8929/8929 [==============================] - 0s 33us/sample - loss: 0.3986 - acc: 0.82470s - loss: 0.3960 - acc: 0.825
Epoch 9/350
8929/8929 [==============================] - 0s 31us

8929/8929 [==============================] - 0s 32us/sample - loss: 0.3305 - acc: 0.8538
Epoch 73/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.3269 - acc: 0.8568
Epoch 74/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.3275 - acc: 0.8558
Epoch 75/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.3263 - acc: 0.8545
Epoch 76/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.3248 - acc: 0.85980s - loss: 0.3248 - acc: 0.859
Epoch 77/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.3236 - acc: 0.8571
Epoch 78/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.3243 - acc: 0.8596
Epoch 79/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.3219 - acc: 0.8587
Epoch 80/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.3197 - acc: 0.85980s - loss: 0.3216 - acc: 0.858
Epoch 81/350
8929/8929 [===========

8929/8929 [==============================] - 0s 32us/sample - loss: 0.2573 - acc: 0.8860
Epoch 146/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2579 - acc: 0.8870
Epoch 147/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.2562 - acc: 0.8886
Epoch 148/350
8929/8929 [==============================] - 0s 30us/sample - loss: 0.2553 - acc: 0.8921
Epoch 149/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2560 - acc: 0.8885
Epoch 150/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.2526 - acc: 0.8898
Epoch 151/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2521 - acc: 0.8921
Epoch 152/350
8929/8929 [==============================] - ETA: 0s - loss: 0.2484 - acc: 0.894 - 0s 32us/sample - loss: 0.2535 - acc: 0.8920
Epoch 153/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.2502 - acc: 0.8924
Epoch 154/350
8929/8929 [========================

8929/8929 [==============================] - 0s 31us/sample - loss: 0.2082 - acc: 0.9120
Epoch 222/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2059 - acc: 0.91570s - loss: 0.1928 - acc: 0.
Epoch 223/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2070 - acc: 0.9120
Epoch 224/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2080 - acc: 0.9140
Epoch 225/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2081 - acc: 0.9176
Epoch 226/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2036 - acc: 0.9150
Epoch 227/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2049 - acc: 0.9130
Epoch 228/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.2028 - acc: 0.9160
Epoch 229/350
8929/8929 [==============================] - 0s 32us/sample - loss: 0.2033 - acc: 0.91540s - loss: 0.1939 - acc: 0.
Epoch 230/350
8929/8929 [========

8929/8929 [==============================] - 0s 31us/sample - loss: 0.1782 - acc: 0.9271
Epoch 297/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.1756 - acc: 0.9250
Epoch 298/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.1750 - acc: 0.9291
Epoch 299/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.1767 - acc: 0.9299
Epoch 300/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.1741 - acc: 0.9297
Epoch 301/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.1724 - acc: 0.9301
Epoch 302/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.1765 - acc: 0.9284
Epoch 303/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.1737 - acc: 0.92850s - loss: 0.1655 - acc: 0.9
Epoch 304/350
8929/8929 [==============================] - 0s 31us/sample - loss: 0.1756 - acc: 0.9252
Epoch 305/350
8929/8929 [==============================] - 

In [26]:
iqi = categorical.predict(x_test)

In [27]:
iqi[0]

array([1., 0.], dtype=float32)

In [28]:
iqi [0] > 0.5

array([ True, False])

In [29]:
dataset.head(50)

age           job   marital  education default  balance housing loan  \
0    59        admin.   married  secondary      no     2343     yes   no   
1    56        admin.   married  secondary      no       45      no   no   
2    41    technician   married  secondary      no     1270     yes   no   
3    55      services   married  secondary      no     2476     yes   no   
4    54        admin.   married   tertiary      no      184      no   no   
5    42    management    single   tertiary      no        0     yes  yes   
6    56    management   married   tertiary      no      830     yes  yes   
7    60       retired  divorced  secondary      no      545     yes   no   
8    37    technician   married  secondary      no        1     yes   no   
9    28      services    single  secondary      no     5090     yes   no   
10   38        admin.    single  secondary      no      100     yes   no   
11   30   blue-collar   married  secondary      no      309     yes   no   
12   29    management   married   tertiary      no      199     yes  yes   
13   46   blue-collar    single   tertiary      no      460     yes   no   
14   31    technician    single   tertiary      no      703     yes   no   
15   35    management  divorced   tertiary      no     3837     yes   no   
16   32   blue-collar    single    primary      no      611     yes   no   
17   49      services   married  secondary      no       -8     yes   no   
18   41        admin.   married  secondary      no       55     yes   no   
19   49        admin.  divorced  secondary      no      168     yes  yes   
20   28        admin.  divorced  secondary      no      785     yes   no   
21   43    management    single   tertiary      no     2067     yes   no   
22   43    management  divorced   tertiary      no      388     yes   no   
23   43   blue-collar   married    primary      no     -192     yes   no   
24   37    unemployed    single  secondary      no      381     yes   no   
25   35   blue-collar    single  secondary      no       40     yes   no   
26   31    technician    single   tertiary      no       22     yes   no   
27   43   blue-collar    single  secondary      no        3     yes   no   
28   31        admin.   married  secondary      no      307     yes   no   
29   28   blue-collar    single  secondary      no      759     yes   no   
30   32   blue-collar   married  secondary     yes       -1     yes   no   
31   60    technician   married    primary      no       65     yes   no   
32   26   blue-collar    single  secondary      no       82     yes   no   
33   40   blue-collar   married  secondary      no       10     yes   no   
34   33   blue-collar  divorced    primary      no      390     yes   no   
35   32    management    single   tertiary      no      311      no   no   
36   35   blue-collar   married    primary      no      414      no   no   
37   33    management  divorced  secondary      no        5     yes   no   
38   38    management   married   tertiary      no      119     yes   no   
39   23  entrepreneur    single    primary      no        4     yes   no   
40   60   blue-collar   married    primary      no     1262     yes  yes   
41   48    management   married   tertiary      no     1949     yes   no   
42   45  entrepreneur  divorced   tertiary      no     -395     yes   no   
43   36   blue-collar   married  secondary      no     1165     yes   no   
44   52    management   married    unknown      no     2240     yes   no   
45   35   blue-collar  divorced    primary      no      300     yes   no   
46   43    technician   married  secondary      no     3285     yes   no   
47   52     housemaid   married  secondary      no     3923     yes   no   
48   53    technician  divorced    primary      no     1443     yes   no   
49   48   blue-collar  divorced    primary      no       24     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome deposit  
0   unknown    5   may      1042         1     -